package com.examly.springapp.enums;

public enum AuditAction {
    REGISTRATION_SUBMITTED,
    PROFILE_UPDATED,
    DOCUMENT_UPLOADED,
    DOCUMENT_VERIFIED,
    DOCUMENT_REJECTED,
    STATUS_CHANGED,
    APPROVED,
    REJECTED,
    SUSPENDED,
    REACTIVATED,
    COMPLIANCE_UPDATED,
    PAYMENT_INFO_UPDATED,
    LOGIN_ATTEMPT,
    PASSWORD_CHANGED,
    CONTACT_UPDATED,
    ADDRESS_UPDATED
}
